apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/store/store
      context: ../store
      jib: {}
    - image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/store/invoice
      context: ../invoice
      jib: {}
    - image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/store/notification
      context: ../notification
      jib: {}
    - image: 702769831180.dkr.ecr.ap-south-1.amazonaws.com/702769831180/store/product
      context: ../product
      jib: {}
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:latest'
deploy:
  kustomize: {}
